#! /usr/bin/env python3

import mt19937


def tests():
    """Test MT19937 in Python."""
    mt19937.drop32(9999)
    mt19937.drop64(9999)

    assert mt19937.rand32() == 0xF5CA0EDB
    assert mt19937.rand64() == 0x8A8592F5817ED872

    mt19937.init32()
    for _ in range(30000):
        modulus = mt19937.rand32()
        assert mt19937.uint32(modulus) < modulus
        left = mt19937.rand32() - 0x80000000
        right = mt19937.rand32() - 0x80000000
        if left < right:
            assert left <= mt19937.span32(left, right) < right

    mt19937.init64()
    for _ in range(30000):
        modulus = mt19937.rand64()
        assert mt19937.uint64(modulus) < modulus
        left = mt19937.rand64() - 0x8000000000000000
        right = mt19937.rand64() - 0x8000000000000000
        if left < right:
            assert left <= mt19937.span64(left, right) < right


def main():
    """Main function."""
    tests()


if __name__ == '__main__':
    main()
