name: deploy
on:
  push:
  schedule:
    - cron: '53 16 */28 * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
      - run: make && ./multigen.py >../../doc/index.html
        working-directory: examples/sudoku/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: doc/
      - uses: actions/deploy-pages@v4
        id: deployment
