name: deploy
on:
  push:
  schedule:
    - cron: '53 */18 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
      - run: make
        working-directory: examples/sudoku/
      - run: |
          (
            printf "<!DOCTYPE html><html><head><title>Sudoku</title></head><body><h1>%s</h1>" "$(date +'%H:%M %Z %A %d %B %Y')"
            printf "<h2>✍️</h2><pre>"
            examples/sudoku/sudoku 11 | sed -e 's/   / ┃ /g' -e 's/^$/  ━━━━━━━━━━━━━━━━━━━━━━━━━━━/g'
            printf "</pre><h2>✍️✍️</h2><pre>"
            examples/sudoku/sudoku 12 | sed -e 's/   / ┃ /g' -e 's/^$/  ━━━━━━━━━━━━━━━━━━━━━━━━━━━/g'
            printf "</pre></body></html>"
          ) >doc/index.html
        env:
          TZ: 'Asia/Kolkata'
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc/'
      - uses: actions/deploy-pages@v4
        id: deployment
